[package]
name = "pepe"
version = "0.1.0"
authors = ["thiolliere <guillaume.thiolliere@opmbx.org>"]

[dependencies]
vulkano = "0.6"
vulkano-shader-derive = "0.6"
vulkano-win = "0.6"
winit = "0.7"
fps_clock = "2"
nalgebra = "0.13"
ncollide = "0.13"
nphysics3d = "0.7"
specs = "0.9"
alga = "0.5"
rand = "0.3"
lazy_static = "0.2"
pathfinding = "0.1"

# app_dirs = "1"
# mut_static = "5"
# serde_derive = "1.0"
# serde_yaml = "0.7"
# serde = "1.0"

# cgmath = "0.14.1"
# image = "0.14.0"
# time = "0.1.37"
